### ISSUE TITLE
[Enhancement] Make ShowUpdateDownload virtual

### ISSUE THREAD

**Issue by micahmo** [Bluegrams/AppHelpers#1]
I really enjoy the `WpfUpdateChecker` component of this library. It is nearly perfect for my needs! However, there is one shortcoming. For portable downloads, the default behavior is to simply open the directory where the file is downloaded.

In my application, I would like to perform some custom action when the file is downloaded, instead of showing it in Explorer. (In my case, I want to copy it to the location of the running executable so that it really does "update" the current portable version. But I can image others would want to perform other custom actions at this step.)

Fortunately, this step is isolated in one method, `UpdateCheckerBase.ShowUpdateDownload`. Unfortunately, there is no way to extend and customize this behavior while retaining all of the other existing functionality in `WpfUpdateChecker`. If it were virtual, it would be a simple matter to inherit from `WpfUpdateChecker`, override `ShowUpdateDownload`, and implement custom handling without calling base.

**Comment by alxnull** [comment]
> I really enjoy the WpfUpdateChecker component of this library. It is nearly perfect for my needs!

I totally didn't expect someone beside myself would find this library and make use of its sparsely documented features :).
Glad you find it useful and thanks for the PR.
